Build_Metadata_Reference: Anti-Features bullet list format that po4a likes
I think this should fix a crash, but I'm just shooting in the dark:

$ jekyll build -d $OUT_DIR --trace
++ echo '$ jekyll build -d $OUT_DIR --trace'
++ jekyll build -d build --trace
Configuration file: /builds/project-0/_config.yml
            Source: /builds/project-0
       Destination: /builds/project-0/build
 Incremental build: disabled. Enable with --incremental
      Generating...
/usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/cache.rb:181:in `initialize': No such file or directory @ rb_sysopen - /builds/project-0/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 (Errno::ENOENT)
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/cache.rb:181:in `open'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/cache.rb:181:in `dump'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/cache.rb:97:in `[]='
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/cache.rb:41:in `clear_if_config_changed'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/site.rb:118:in `reset'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/site.rb:77:in `process'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:106:in `process_active_language'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:90:in `process_language'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:41:in `block (2 levels) in process'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:40:in `fork'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:40:in `block in process'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:39:in `each'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:39:in `process'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/exe/jekyll:13:in `<top (required)>'
        from /usr/bin/jekyll:25:in `load'
        from /usr/bin/jekyll:25:in `<main>'
/var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:49:in `block (2 levels) in process': Polyglot subprocess 11006 (ar) failed (1) (RuntimeError)
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:45:in `each'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:45:in `map'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:45:in `block in process'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:39:in `each'
        from /var/lib/gems/3.1.0/bundler/gems/jekyll-polyglot-b4520fd8c638/lib/jekyll/polyglot/patches/jekyll/site.rb:39:in `process'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/share/rubygems-integration/all/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/share/rubygems-integration/all/gems/jekyll-4.3.1/exe/jekyll:13:in `<top (required)>'
        from /usr/bin/jekyll:25:in `load'
        from /usr/bin/jekyll:25:in `<main>'
ERROR: Job failed: exit code 1